### ISSUE TITLE
package-lock.json missing form git

### ISSUE THREAD

**Issue by Ten0** [blakewest/performer#3]
The `package-lock.json` file is missing form the repository. Libs were updated quite a lot since then, and it doesn't work anymore.

Probably related to #2.

**Comment by blakewest** [comment]
@Ten0 yeah, that's fair, if you did a fresh install, then indeed the packages have been updated heavily since this was originally written, which was like 5 years ago now. That said, it's a rather small repo, and I originally did the whole thing in 2 weeks start to finish anyway, and I was a pretty junior developer then. So I feel confident that with a little love, we could track down the broken packages, and fix this. The core logic definitely is all still "correct". It's just a matter of finding out which calls stopped working.

**Comment by Ten0** [comment]
The clean way to fix it would indeed be to fix the packages calls, though if you still have a working install from then somewhere on a computer, maybe simply retrieving the package-lock.json to reinstall the older packages versions would get it back

**Comment by blakewest** [comment]
@Ten0 Hey! I fixed it. There were a few random issues that seemed to only really be in effect on new installs. Much of this was due to a poor design choice on my part where when the app loaded, if you didn't have any cached songs in your db, the app just would never start, and would fail. Yeah, remember I said I was pretty junior when I wrote this? 😆 . Anyway, it's at least fixed now, and it appears to work! Yay! Super happy about this. Please let me know if you can get it to work on your side too! And hope it proves useful and/or fun to you.
